"""Factorio Learning Environment wrapper for GRPO training.

Manages FLE cluster lifecycle and evaluates generated Python code
by executing it in Factorio game instances.
"""

import atexit
import subprocess
import time
from typing import Any, Dict, List, Optional

try:
    import gymnasium as gym
    from fle.env.gym_env.action import Action
    _FLE_AVAILABLE = True
except ImportError:
    _FLE_AVAILABLE = False


def _ensure_fle():
    if not _FLE_AVAILABLE:
        raise ImportError(
            "factorio-learning-environment is required. "
            "Install with: uv add factorio-learning-environment"
        )


class FactorioCluster:
    """Manages the FLE server cluster lifecycle."""

    def __init__(self):
        self._process: Optional[subprocess.Popen] = None

    def start(self):
        """Start the FLE cluster via CLI."""
        if self._process is not None:
            return
        print("Starting FLE cluster...")
        self._process = subprocess.Popen(
            ["fle", "cluster", "start"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        # Give the cluster time to initialize
        time.sleep(10)
        print("FLE cluster started.")
        atexit.register(self.stop)

    def stop(self):
        """Stop the FLE cluster."""
        if self._process is None:
            return
        print("Stopping FLE cluster...")
        subprocess.run(["fle", "cluster", "stop"], capture_output=True)
        self._process = None

    def __enter__(self):
        self.start()
        return self

    def __exit__(self, *args):
        self.stop()


class FactorioRewardEvaluator:
    """Evaluates generated Python code in the Factorio environment.

    For single-turn GRPO training: the model generates one Python program,
    we execute it in FLE, and score the outcome.
    """

    def __init__(self, manage_cluster: bool = True):
        """Initialize the evaluator.

        Args:
            manage_cluster: If True, start/stop the FLE cluster automatically.
        """
        _ensure_fle()
        self._cluster = FactorioCluster() if manage_cluster else None
        self._env: Optional[Any] = None
        self._current_env_id: Optional[str] = None

    def start(self):
        """Start the cluster if managed."""
        if self._cluster is not None:
            self._cluster.start()

    def stop(self):
        """Clean up environments and cluster."""
        if self._env is not None:
            self._env.close()
            self._env = None
        if self._cluster is not None:
            self._cluster.stop()

    def _get_env(self, env_id: str):
        """Get or create a gym environment for the given task."""
        if self._current_env_id != env_id:
            if self._env is not None:
                self._env.close()
            self._env = gym.make(env_id)
            self._current_env_id = env_id
        return self._env

    def evaluate(self, code: str, task_config: Dict[str, Any]) -> float:
        """Execute code in FLE and return a reward score.

        Args:
            code: Python code string generated by the model.
            task_config: Task configuration with 'env_id' and metadata.

        Returns:
            Reward float:
                1.0 — task objective achieved
                0.5 — code ran without errors but objective not met
                0.1 — code had runtime errors but produced some state change
                0.0 — code failed to parse or execute entirely
        """
        env_id = task_config["env_id"]
        env = self._get_env(env_id)

        try:
            obs, info = env.reset(options={"game_state": None})
        except Exception as e:
            print(f"[FactorioEval] Environment reset failed: {e}")
            return 0.0

        # Execute the generated code as a single step
        try:
            action = Action(agent_idx=0, game_state=None, code=code)
            obs, reward, terminated, truncated, info = env.step(action)
        except Exception as e:
            print(f"[FactorioEval] Step execution error: {e}")
            return 0.0

        # Check task verification for success
        task_verification = obs.get("task_verification", {}) if isinstance(obs, dict) else {}
        task_success = False
        if isinstance(task_verification, dict):
            task_success = task_verification.get("success", False)
        elif hasattr(task_verification, "success"):
            task_success = task_verification.success

        if task_success:
            return 1.0

        # Check if code ran without errors (raw_text won't contain traceback)
        raw_text = obs.get("raw_text", "") if isinstance(obs, dict) else ""
        has_error = "Error" in raw_text or "Traceback" in raw_text

        if not has_error and reward > 0:
            return 0.5
        elif not has_error:
            return 0.25
        elif reward > 0:
            return 0.1
        else:
            return 0.0

    def batch_evaluate(
        self, codes: List[str], task_configs: List[Dict[str, Any]]
    ) -> List[float]:
        """Evaluate a batch of code completions sequentially.

        Args:
            codes: List of Python code strings.
            task_configs: Corresponding task configs (one per code).

        Returns:
            List of reward floats.
        """
        rewards = []
        for code, config in zip(codes, task_configs):
            r = self.evaluate(code, config)
            rewards.append(r)
        return rewards

    def __enter__(self):
        self.start()
        return self

    def __exit__(self, *args):
        self.stop()
